param(
  [string]$GameRoot = "E:\GAME\Wayward",
  [string]$Character = "elena",
  [switch]$ResetCharacterArt,
  [switch]$InstallDevelopmentConfig,
  [switch]$KeepDevelopmentTestArtifacts
)

$ErrorActionPreference = "Stop"

$SourceRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$TargetRoot = Join-Path $GameRoot "wayward-imagegen"

function Write-Step([string]$Message) {
  Write-Host ""
  Write-Host "== $Message ==" -ForegroundColor Cyan
}

function Write-Utf8NoBom([string]$Path, [string]$Text) {
  [System.IO.File]::WriteAllText(
    $Path,
    $Text,
    (New-Object System.Text.UTF8Encoding($false))
  )
}

function Get-ProductionArtSnapshot([string]$BackendRoot, [string]$WaywardRoot) {
  $charactersRoot = Join-Path $BackendRoot "images\illustrious\characters"
  $files = @()
  if (Test-Path $charactersRoot) {
    $files = @(Get-ChildItem $charactersRoot -File -Recurse -ErrorAction SilentlyContinue)
  }

  [long]$totalBytes = 0
  foreach ($file in $files) {
    $totalBytes += [long]$file.Length
  }

  $cachePath = Join-Path $BackendRoot "images\.image-cache.json"
  $cacheHash = $null
  if (Test-Path $cachePath) {
    $cacheHash = (Get-FileHash $cachePath -Algorithm SHA256).Hash
  }

  $activeManifests = @(
    Get-ChildItem $WaywardRoot -File -Filter "images-*.js" -ErrorAction SilentlyContinue |
      Sort-Object Name |
      ForEach-Object { $_.Name }
  )
  $disabledRoot = Join-Path $WaywardRoot "_disabled-imagepacks"
  $disabledManifests = @()
  if (Test-Path $disabledRoot) {
    $disabledManifests = @(
      Get-ChildItem $disabledRoot -File -Recurse -Filter "images-*.js" -ErrorAction SilentlyContinue |
        Sort-Object FullName |
        ForEach-Object { $_.FullName.Substring($WaywardRoot.Length).TrimStart("\") }
    )
  }

  return [PSCustomObject]@{
    GeneratedFileCount = $files.Count
    GeneratedBytes = $totalBytes
    CacheHash = $cacheHash
    ActiveManifests = ($activeManifests -join "|")
    DisabledManifests = ($disabledManifests -join "|")
  }
}

function Assert-ProductionArtPreserved($Before, $After) {
  $changes = @()
  if ($Before.GeneratedFileCount -ne $After.GeneratedFileCount) {
    $changes += "generated file count: $($Before.GeneratedFileCount) -> $($After.GeneratedFileCount)"
  }
  if ($Before.GeneratedBytes -ne $After.GeneratedBytes) {
    $changes += "generated bytes: $($Before.GeneratedBytes) -> $($After.GeneratedBytes)"
  }
  if ($Before.CacheHash -ne $After.CacheHash) {
    $changes += "image cache hash changed"
  }
  if ($Before.ActiveManifests -ne $After.ActiveManifests) {
    $changes += "active static-image manifests changed"
  }
  if ($Before.DisabledManifests -ne $After.DisabledManifests) {
    $changes += "disabled static-image manifests changed"
  }

  if ($changes.Count -gt 0) {
    throw ("Production-art preservation check failed: " + ($changes -join "; "))
  }
}
function Remove-CharacterCacheEntries([string]$CachePath, [string]$CharacterName) {
  if (-not (Test-Path $CachePath)) {
    Write-Host "No cache index to prune: $CachePath"
    return
  }

  $cache = Get-Content $CachePath -Raw | ConvertFrom-Json
  if (-not $cache.entries) {
    Write-Host "Cache index has no entries."
    return
  }

  $kept = [ordered]@{}
  $removed = 0
  $prefix = ($CharacterName.ToLowerInvariant() + "__")

  foreach ($property in $cache.entries.PSObject.Properties) {
    $talentName = [string]$property.Value.talentName
    if ($talentName.ToLowerInvariant().StartsWith($prefix)) {
      $removed++
    }
    else {
      $kept[$property.Name] = $property.Value
    }
  }

  $cache.entries = [PSCustomObject]$kept
  Write-Utf8NoBom $CachePath ($cache | ConvertTo-Json -Depth 50)
  Write-Host "Removed $removed cache entries for $CharacterName; kept $($kept.Count)."
}

Write-Step "Preflight"

if (-not (Test-Path (Join-Path $SourceRoot "src\cli.ts"))) {
  throw "Source repository does not look valid: $SourceRoot"
}
if (-not (Test-Path $TargetRoot)) {
  throw "Wayward backend folder not found: $TargetRoot"
}

$listen = Get-NetTCPConnection -LocalPort 8189 -State Listen -ErrorAction SilentlyContinue
if ($listen) {
  throw "Port 8189 is still in use. Stop the running wayward-imagegen server first, then rerun this script."
}

Write-Host "Source : $SourceRoot"
Write-Host "Target : $TargetRoot"

$preserveSnapshot = $null
if (-not $ResetCharacterArt) {
  $preserveSnapshot = Get-ProductionArtSnapshot $TargetRoot $GameRoot
  Write-Host ("Preserve snapshot: {0} generated files / {1:N2} MB" -f $preserveSnapshot.GeneratedFileCount, ($preserveSnapshot.GeneratedBytes / 1MB))
}

Write-Step "Back up the current production config"

$targetConfig = Join-Path $TargetRoot "wayward-imagegen.config.json"
$backupDir = Join-Path $SourceRoot "deployment-backup"
New-Item -ItemType Directory -Path $backupDir -Force | Out-Null

if (Test-Path $targetConfig) {
  $stamp = Get-Date -Format "yyyyMMdd-HHmmss"
  $backupConfig = Join-Path $backupDir "wayward-imagegen.config.$stamp.json"
  Copy-Item $targetConfig $backupConfig -Force
  Write-Host "Config backup: $backupConfig"
}
else {
  Write-Host "No existing production config."
}

Write-Step "Replace production backend code with the tested Anima build"

foreach ($dir in @("src", "ui", "scripts")) {
  $target = Join-Path $TargetRoot $dir
  if (Test-Path $target) {
    Remove-Item $target -Recurse -Force
  }
  Copy-Item (Join-Path $SourceRoot $dir) $target -Recurse -Force
}

foreach ($file in @(
  "package.json",
  "README.md",
  "ANIMA_SETUP.md",
  "DISTRIBUTION.md",
  "NOTICE.md",
  "LICENSE",
  "wayward-imagegen.config.example.json",
  "wayward-imagegen.config.anima.example.json"
)) {
  $source = Join-Path $SourceRoot $file
  if (Test-Path $source) {
    Copy-Item $source (Join-Path $TargetRoot $file) -Force
  }
}

Write-Step "Preserve/install production configuration"

$sourceConfig = Join-Path $SourceRoot "wayward-imagegen.config.json"
if ((Test-Path $targetConfig) -and -not $InstallDevelopmentConfig) {
  Write-Host "Keeping existing production config:"
  Write-Host "  $targetConfig"
}
elseif ($InstallDevelopmentConfig) {
  if (-not (Test-Path $sourceConfig)) {
    throw "Development config requested but not found: $sourceConfig"
  }

  $config = Get-Content $sourceConfig -Raw | ConvertFrom-Json
  $config.imagesDir = "images"
  if ($config.PSObject.Properties.Name -contains "stateDir") {
    if ([string]$config.stateDir -like "*images-quality-test*") {
      $config.stateDir = "images\.state"
    }
  }
  Write-Utf8NoBom $targetConfig ($config | ConvertTo-Json -Depth 50)
  Write-Host "Installed development config into production:"
  Write-Host "  $targetConfig"
}
else {
  if (Test-Path $targetConfig) {
    Remove-Item $targetConfig -Force
  }
  Write-Host "No config installed. The first-run browser wizard will create one."
}

$imagesRoot = Join-Path $TargetRoot "images"

if ($ResetCharacterArt) {
  Write-Step "Reset only the production character art"
  
  New-Item -ItemType Directory -Path $imagesRoot -Force | Out-Null
  
  $characterDir = Join-Path $imagesRoot ("illustrious\characters\" + $Character)
  if (Test-Path $characterDir) {
    Remove-Item $characterDir -Recurse -Force
    Write-Host "Deleted generated art: $characterDir"
  }
  else {
    Write-Host "No existing generated art folder for $Character."
  }
  
  Remove-CharacterCacheEntries (Join-Path $imagesRoot ".image-cache.json") $Character
  
  $legacyCharacterDir = Join-Path $GameRoot ("images\illustrious\characters\" + $Character)
  if (Test-Path $legacyCharacterDir) {
    Remove-Item $legacyCharacterDir -Recurse -Force
    Write-Host "Deleted legacy/shipped game-root art so Wayward will request fresh renders:"
    Write-Host "  $legacyCharacterDir"
  }
  else {
    Write-Host "No game-root legacy art folder for $Character."
  }
  
  # The downloaded image pack has two parts: the image files under images/ and
  # one or more images-<character>-*.js manifests next to index.html. Leaving the
  # manifests behind after deleting the files makes the game still believe that
  # the static pack is installed. Move only this character's manifests aside so
  # fresh local-generation requests are authoritative, while keeping an easy
  # rollback copy.
  $disabledPackDir = Join-Path $GameRoot ("_disabled-imagepacks\" + $Character)
  $packManifests = @(Get-ChildItem -Path $GameRoot -File -Filter ("images-" + $Character + "-*.js") -ErrorAction SilentlyContinue)
  if ($packManifests.Count -gt 0) {
    New-Item -ItemType Directory -Path $disabledPackDir -Force | Out-Null
    foreach ($manifest in $packManifests) {
      $dest = Join-Path $disabledPackDir $manifest.Name
      Move-Item $manifest.FullName $dest -Force
      Write-Host "Disabled static image-pack manifest:"
      Write-Host "  $($manifest.FullName)"
      Write-Host "  -> $dest"
    }
  }
  else {
    Write-Host "No static image-pack manifests found for $Character."
  }
  
  $batchDir = Join-Path $imagesRoot ".state\batch"
  if (Test-Path $batchDir) {
    Remove-Item $batchDir -Recurse -Force
    Write-Host "Cleared old batch state."
  }
  
  
}
else {
  Write-Step "Preserve existing generated/static character art"
  Write-Host "Character art reset skipped. Use -ResetCharacterArt only when a clean regeneration is intentional."
}

Write-Step "Remove known test-only artifacts from the production backend"

foreach ($name in @("images-quality-test", "AB-anima-models")) {
  $path = Join-Path $TargetRoot $name
  if (Test-Path $path) {
    Remove-Item $path -Recurse -Force
    Write-Host "Removed: $path"
  }
}

if (-not $KeepDevelopmentTestArtifacts) {
  Write-Step "Remove known generated test artifacts from the development repository"
  foreach ($name in @("images-quality-test", "AB-anima-models")) {
    $path = Join-Path $SourceRoot $name
    if (Test-Path $path) {
      Remove-Item $path -Recurse -Force
      Write-Host "Removed: $path"
    }
  }
}

Write-Step "Install one-click Wayward launcher"

$launcherSource = Join-Path $SourceRoot "scripts\wayward-ai-launcher.ps1"
$launcherPs1 = Join-Path $GameRoot "Wayward-AI.ps1"
$launcherCmd = Join-Path $GameRoot "Wayward-AI.cmd"

Copy-Item $launcherSource $launcherPs1 -Force

$launcherCmdText = @'
@echo off
powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%~dp0Wayward-AI.ps1"
if errorlevel 1 pause
'@
[System.IO.File]::WriteAllText(
  $launcherCmd,
  $launcherCmdText,
  [System.Text.Encoding]::ASCII
)

Write-Host "Launcher installed:"
Write-Host "  $launcherCmd"

Write-Step "Production validation"

Push-Location $TargetRoot
try {
  & bun scripts\smoke.ts
  if ($LASTEXITCODE -ne 0) {
    throw "Smoke test failed."
  }

  $comfyUrl = "http://127.0.0.1:8188"
  if (Test-Path $targetConfig) {
    try {
      $deployedConfig = Get-Content $targetConfig -Raw | ConvertFrom-Json
      if (-not [string]::IsNullOrWhiteSpace([string]$deployedConfig.comfyUrl)) {
        $comfyUrl = ([string]$deployedConfig.comfyUrl).TrimEnd("/")
      }
    }
    catch {
      Write-Host "Could not parse production config for ComfyUI preflight." -ForegroundColor Yellow
    }
  }

  $comfyReady = $false
  try {
    $null = Invoke-WebRequest -UseBasicParsing -Uri ($comfyUrl + "/system_stats") -TimeoutSec 3
    $comfyReady = $true
  }
  catch {
    $comfyReady = $false
  }

  if ($comfyReady) {
    & bun src\cli.ts doctor
    if ($LASTEXITCODE -ne 0) {
      throw "Doctor failed."
    }
  }
  else {
    Write-Host "ComfyUI is not currently reachable at $comfyUrl." -ForegroundColor Yellow
    Write-Host "Skipping live doctor; smoke test passed and deployment is otherwise complete."
    Write-Host "Run 'bun src\cli.ts doctor' later with ComfyUI running for the live model check."
  }
}
finally {
  Pop-Location
}

if (-not $ResetCharacterArt -and $preserveSnapshot) {
  Write-Step "Verify production art was preserved"
  $afterSnapshot = Get-ProductionArtSnapshot $TargetRoot $GameRoot
  Assert-ProductionArtPreserved $preserveSnapshot $afterSnapshot
  Write-Host ("Verified unchanged: {0} generated files / {1:N2} MB, cache and static-pack state preserved." -f $afterSnapshot.GeneratedFileCount, ($afterSnapshot.GeneratedBytes / 1MB))
}

Write-Step "Ready"

Write-Host "Production backend:"
Write-Host "  $TargetRoot"
Write-Host ""
Write-Host "New $Character images will be generated into:"
Write-Host "  $(Join-Path $imagesRoot ("illustrious\characters\" + $Character))"
Write-Host ""
if ($ResetCharacterArt) {
  Write-Host "The old $Character generated art/cache and game-root legacy art were reset."
}
else {
  Write-Host "Existing generated art, cache and static image packs were preserved."
}
Write-Host "Normal use:"
Write-Host "  1. Start ComfyUI."
Write-Host "  2. Double-click $(Join-Path $GameRoot "Wayward-AI.cmd")."
Write-Host "The launcher starts wayward-imagegen when needed and then opens Wayward."
